In [1]:
import numpy as np

# Q1. Check the data types of variables list_ and array_list
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Q1. Data types of variables:")
print("Type of list_:", type(list_))
print("Type of array_list:", type(array_list))

# Q2. Print the data type of each element of list_ and array_list
print("\nQ2. Data type of each element:")
print("Data types in list_:", [type(item) for item in list_])
print("Data types in array_list:", [type(item) for item in array_list])

# Q3. Change dtype of array_list and compare data types
array_list = np.array(object=list_, dtype=int)

print("\nQ3. Data types after converting array_list to int:")
print("Data types in list_:", [type(item) for item in list_])
print("Data types in array_list:", [type(item) for item in array_list])

# Q4. Find shape and size of num_array
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("\nQ4. Characteristics of num_array:")
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)

# Q5. Create a 3x3 matrix containing zeros only
zeros_matrix = np.zeros((3, 3))
print("\nQ5. 3x3 matrix of zeros:")
print(zeros_matrix)

# Q6. Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("\nQ6. 5x5 identity matrix:")
print(identity_matrix)


Q1. Data types of variables:
Type of list_: <class 'list'>
Type of array_list: <class 'numpy.ndarray'>

Q2. Data type of each element:
Data types in list_: [<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]
Data types in array_list: [<class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>]

Q3. Data types after converting array_list to int:
Data types in list_: [<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]
Data types in array_list: [<class 'numpy.int32'>, <class 'numpy.int32'>, <class 'numpy.int32'>, <class 'numpy.int32'>, <class 'numpy.int32'>]

Q4. Characteristics of num_array:
Shape of num_array: (2, 3)
Size of num_array: 6

Q5. 3x3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Q6. 5x5 identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
